---
- hosts: devicat # хосты объявлены в inventory-файле для каждого окружения
  remote_user: 'root'
  # В данном блоке объявляются переменные, которые будут использоваться в playbook и конфигах, представленных выше
  vars:

    # Пользователь, от лица которого будет происходит деплой
    user: 'deployer'
        # Домашняя директория
    home: '/home/{{ user }}'
    # Название приложения
    app_name: 'devicat'
    app_site: '{{ app_name }}.echelonsystems.ru'
    # Путь до нашего приложения
    application: '{{ home }}/applications/{{ app_name }}'

  handlers:
    - name: Restart sshd
      service:
        name: 'ssh'
        state: 'restarted'

    - name: restart nginx
      service: name=nginx state=restarted

    - name: validate nginx configuration
      command: nginx -t -c /etc/nginx/nginx.conf
      changed_when: False

    - name: reload nginx
      service: name=nginx state=reloaded

  tasks:
    - include_tasks: 'tasks/prepare.yml'
    #- include: release.yml # создание нового релиза
    #- include: app.yml     # запуск сервера веб-прриложения
    #- include: sidekiq.yml # запуск воркеров sidekiq
