---

- name: Detect if rubies are installed
  command: '{{ rvm_binary_path }} {{ item }} do true'
  changed_when: False
  failed_when: False
  register: detect_rubies
  with_items: '{{ ruby_version }}'
  when: ruby_version



# - name: installing Ruby as root
#   command: "{{rvm_binary_path}} install {{ruby_version}}"
#   register: output
# - debug: var=detect_rubies.results
#detect_rubies.stdout_lines
# - debug: msg="{{ output.stdout }}"

# - debug: msg="{{ output.stderr }}"

# - name: setting default Ruby version as root
#   shell: "source {{rvm_init_script}} && rvm use {{ruby_version}} --default executable=/bin/bash"
#   ignore_errors: True
#   changed_when: False



- name: Install rubies
  command: '{{ rvm_binary_path }} install {{ item.item }}'
  when: ruby_version and item.rc|default(0) != 0
  with_items: '{{ detect_rubies.results }}'

- name: Detect default ruby version
  command: '{{ rvm_binary_path }} alias list default'
  changed_when: False
  register: detect_default_ruby_version

- name: Select default ruby
  command: '{{ rvm_binary_path }} alias create default {{ rvm_default_ruby_version }}'
  when: detect_default_ruby_version.stdout|default() == "" or
        rvm_default_ruby_version not in detect_default_ruby_version.stdout


- name: Detect installed ruby patch number
  shell: >
    {{ rvm_binary_path }} list strings | grep {{ item }} | tail -n 1
  with_items: '{{ ruby_version }}'
  changed_when: False
  register: ruby_patch
  check_mode: no

- name: Install bundler if not installed
  shell: >
    ls {{ rvm_install_path }}/wrappers/{{ item.stdout }}
    | if ! grep "^bundler " ; then {{ rvm_install_path }}/wrappers/{{ item.stdout }}/gem install bundler ; fi
  args:
    creates: '{{ rvm_install_path }}/wrappers/{{ item.stdout }}/bundler'
  with_items: '{{ ruby_patch.results }}'
  when: rvm_bundler_install
  register: bundler_install
  changed_when: '"Successfully installed bundler" in bundler_install.stdout'

- name: Symlink ruby related binaries on the system path
  file:
    state: 'link'
    src: '{{ rvm_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
  when: not '--user-install' in rvm_install_flags
  with_items: '{{ rvm_symlink_binaries }}'

- name: Symlink bundler binaries on the system path
  file:
    state: 'link'
    src: '{{ rvm_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
  when: not '--user-install' in rvm_install_flags and rvm_bundler_install
  with_items: '{{ rvm_symlink_bundler_binaries }}'




# host_key_checking = False
# private_key_file = ~/.ssh/id_rsa
