---

- name: Check for mpapis gpg key as root
  shell: gpg --list-keys mpapis
  register: mpapis_gpg_key_exists
  ignore_errors: true

- name: receiving key as root
  shell: "curl -sSL https://rvm.io/mpapis.asc | gpg --import -"
  when: mpapis_gpg_key_exists is defined and mpapis_gpg_key_exists.rc is defined and mpapis_gpg_key_exists.rc != 0
